client:
  hosts:
    - elastic
  port: 9200
  url_prefix:
  use_ssl: ${USE_SSL:False}
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False
  http_auth: ${HTTP_AUTH:''}
  timeout: ${TIMEOUT:120}
  master_only: ${MASTER_ONLY:True}
logging:
  loglevel: INFO
  logfile:
  logformat: default
  #blacklist: ['elasticsearch', 'urllib3']
