elasticsearch:
  client:
    hosts: http://elastic:9200
    request_timeout: 60
    client_cert:
    client_key:
  other_settings:
    master_only: ${MASTER_ONLY:True}
    skip_version_test:
    username: user
    password: 1qazxsw2
    api_key:
      id:
      api_key:
logging:
  loglevel: INFO
  logfile:
  logformat: default
