services:
  emby:
    image: lscr.io/linuxserver/emby:4.8.10
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - /d/plex:/multimedia
      - /d/cloud:/cloud
    ports:
      - 8096:8096
#      - 8920:8920 #optional - https
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
