filebeat.autodiscover:
  providers:
    - type: docker
      hints:
        enabled: true
        default_config:
          enabled: false
          paths:
          - /var/lib/docker/containers/${data.container.id}/*.log
          type: container

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - decode_json_fields:
      fields: [ "message" ]
      target: ""
      overwrite_keys: true

output.elasticsearch:
  hosts: [ "elastic:9200" ]
  indices:
    - index: "%{[docker.container.labels.com_docker_compose_service]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false
